version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env


volumes:
  postgres-db:
